### ISSUE TITLE
Create environment for project

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/predict-airbnb-nightly-price#4]
We should used Docker to create an environment we can share. How about we use this base image: [jupyter/scipy-notebook](https://github.com/jupyter/docker-stacks/blob/master/scipy-notebook/Dockerfile)?

What other packages do we need to add?

**Comment by mds-octocat** [comment]
I think we might want to use a simpler Docker image (such as [`ubcdsci/jupyterlab`](https://hub.docker.com/repository/docker/ubcdsci/jupyterlab)) and also use an `environment.yml` file so that we can also leverage conda at times if we want?

**Comment by ttimbers** [comment]
Good idea! I'll open a PR for this if you could kindly review it?
